### ISSUE TITLE
Consider ordering of values

### ISSUE THREAD

**Issue by justinlittman** [dcmi/dctap#14]
For mapping Sinopia (BIBFRAME) Profiles to DCTAP (see https://github.com/LD4P/dctap), we need to be able to specify that a property is ordered.

We always use RDF lists for ordering. However, you can imagine generalizing this attribute to allow specifying the ordering implementation, e.g., `LIST` or `SEQ`.

**Comment by kcoyle** [comment]
@justinlittman We punted on ordering of properties (see [this](https://github.com/dcmi/dcap/issues/26)) because it requires relationships that go across rows, something that CSV does not accommodate. I suppose we could add a column for order, but then there is the complication between overall order and order within shapes. (I'm available to chat about this or any other questions.) Again, this may be a "post-csv" feature if we can't make it work within the CSV environment. Would you be interested in working with us on this?

**Comment by justinlittman** [comment]
Clarification: This would be ordering of values (i.e., within the row), not properties.

**Comment by kcoyle** [comment]
Oh, I may need an example. Are you talking about when you have multiple values in a cell, like "red,blue,green"? If so, I could imagine a value constraint type like "orderedList" with the order being what is given as the value constraint.

Or - tell me what you really mean ;-)

**Comment by justinlittman** [comment]
The ordering applies to the values of the property, where the values can be (of course) a literal, IRI, or blank node.

For example, here is an ordered literal:
```
<> <http://id.loc.gov/ontologies/bibframe/responsibilityStatement> _:b1.
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b2;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "Erich Gamma"@eng.
_:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b3;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "Richard Helm"@eng.
_:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b4;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "Ralph Johnson"@eng.
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "John Vlissides"@eng.
```

And here is an ordered blank node:
```
<> <http://id.loc.gov/ontologies/bibframe/extent> _:b1.
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b2;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:b3.
_:b3 a <http://id.loc.gov/ontologies/bibframe/Extent>;
    <http://www.w3.org/2000/01/rdf-schema#label> "28 cm."@eng;
    <http://id.loc.gov/ontologies/bibframe/note> _:b4.
_:b4 a <http://id.loc.gov/ontologies/bibframe/Note>;
    <http://www.w3.org/2000/01/rdf-schema#label> "Approximate."@eng.
_:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:b5.
_:b5 a <http://id.loc.gov/ontologies/bibframe/Extent>;
    <http://www.w3.org/2000/01/rdf-schema#label> "9 inches"@eng.
```

(In all of my examples ignore the faux cataloging. Not a cataloger.)

**Comment by philbarker** [comment]
@justinlittman If I understand you correctly, you want the instance data to be ordered, and want to use and RDF:List to do the ordering. So your TAP would say that the value of certain properties should have the shape of an RDF:List with certain properties. Something along the lines of this for your first example:

| shapeID	        | propertyID                           | valueNodeType   | valueShape    |  valueConstraint |
| -----------         | ---------------                           |  --------------------  | ----------------    | ---------------------- |
|                       |  bib:responsibilityStatement | BNODE              |  statementList |                            |
| statementList |  rdf:first                                 |  LITERAL           |                        |                            |
|                       |  rdf:rest                                 | BNODE             |  statementList  |                            |

(and yes, this doesn't cover allowing RDF:nil as a URI for the last item -- that's related to issue #12  )

Or am I missing the point?

**Comment by kcoyle** [comment]
Thanks, @justinlittman. 

It seems that you need a way to say that all of the instance values for a given property must be ordered, and the ordering itself will take place on the instance data. This would be applicable to repeatable properties. Is this correct? If so there would be something like:

propertyID|mandatory|repeatable|ordered|
 ---- |----|----| ---- | 
dct:subject|true|true|true|

And then as data is created an array would be assumed:

dct:subject {0} Dogs {1} Cats {3} Mice

I'm not sure where the ordering will come from, but if it is humans doing input then the input order would be the order. ? 

Thanks again for your examples! These really help us understand the real world needs.

**Comment by kcoyle** [comment]
I want to add that I think we also have a case for ordering *properties*. Using Justin's example from #13 this could look like:

Ordered properties within a shape would be entered in different rows in the table or CSV. The CSV file would (always?) retain the order, which again could be carried forward. This, I believe, is your ISBN example where ISBN is a shape with various properties, like value, qualifier, note. If you desire a specific statement of order you could add a local column for order number which your applications would then use.

shapeID|shapeLabel|propertyID|propertyLabel|mandatory|repeatable|orderNo|valueNodeType|valueDataType|valueConstraint|valueConstraintType|valueShape|note
----|----|---- | ---- |----|----| ---- | ---- |---- | ----|----|----|----
pcc:bf2:Identifiers:ISBN|Identifiers--ISBN|http://www.w3.org/1999/02/22-rdf-syntax-ns#type|Class|true|false|1||IRI|http://id.loc.gov/ontologies/bibframe/Isbn||
pcc:bf2:Identifiers:ISBN|Identifiers--ISBN|http://sinopia.io/vocabulary/hasResourceTemplate|Profile ID|false|false|2||LITERAL|pcc:bf2:Identifiers:ISBN||
pcc:bf2:Identifiers:ISBN|Identifiers--ISBN|http://www.w3.org/1999/02/22-rdf-syntax-ns#value|ISBN|false|false|3||LITERAL|||
pcc:bf2:Identifiers:ISBN|Identifiers--ISBN|http://id.loc.gov/ontologies/bibframe/qualifier|Qualifier|false|false|4||LITERAL|||
pcc:bf2:Identifiers:ISBN|Identifiers--ISBN|http://id.loc.gov/ontologies/bibframe/note|Note|false|true|5||BNODE||pcc:bf2:Note:GeneralNote|
pcc:bf2:Identifiers:ISBN|Identifiers--ISBN|http://id.loc.gov/ontologies/bibframe/status|"Incorrect, Invalid or Canceled?"|false|true|6||LITERAL|IRI||sinopia:LabeledResource|

A column of this nature could be added to the TAP, of course, but we hesitated because we had questions relating to ordering properties and ordering shapes, and we simply haven't thought that through. If we can limit to ordering only properties within each shape, then that may make the requirement more implementable. If we must order both shapes and properties that would require two separate columns. 

I think I should do this as a separate issue so we don't get confused here.

**Comment by justinlittman** [comment]
Responses to various questions from above:

For what it is worth, on order properties: RDF parsers are erratic about ordering. Thus, even if my RDF has properties in a specific order, the parser cannot be counted on to return the properties in that order. (Same with values, unless you use a mechanism like an RDF List or Sequence. I've learned this the hard way.)

Since there are multiple mechanisms for ordering within RDF, I'd suggest that the ordering attribute allow specifying which mechanism to use. (Again, we use RDF Lists for Sinopia, but you can imagine using an RDF Sequence.)

Within Sinopia, for properties that are ordered, the cataloger can provide the values (whether literal or blank node resource) in the desired order and change that order.

Yes, something like the statementList approach could be used. However, I'd suggest that it is less human-understandable than a separate "ordered" attribute. (At least for me, part of the goal for using DCTAP is for communication with catalogers who may not be fully versed in RDF, but need to understand the shape of the data.)

**Comment by kcoyle** [comment]
@justinlittman If it's ok with you I will split this into two issues: order of values for a property, order of properties in a shape. Thumbs up or down, thanks.

**Comment by justinlittman** [comment]
Up.

**Comment by kcoyle** [comment]
Getting back to this, I'm wondering if we can't conclude that ordered values are an extension to our `valueConstraint` list. The method of ordering could be given in the `valueConstraintType`.

propertyID|mandatory|repeatable|valueConstraint|valueConstraintType|
 ---- |----|----| ---- | ----|
dct:subject|true|true|orderedList|rdf:List|

If folks think this is at least one viable possibility, I will add it to the draft of the [Cookbook](https://hackmd.io/V3LGdBdxTrOid57M2wJUlw), which is where we will offer solutions that go beyond the basic TAP.

**Comment by justinlittman** [comment]
Would that preclude specifying a `valueContraint` for the list values? Like "this should be an ordered list with the IRIStem of `http://id.loc.gov/`."

**Comment by kcoyle** [comment]
Ah, good catch, @justinlittman . Dang! OK, back to the drawing board. 

If we add columns for orderedList and type, are there other functions that might use those same columns? I'm thinking (vaguely) about other processing functions that could be expressed if we generalize this. Could this become the place where we can add some AND OR NOT rules? For example, if we have foaf:firstName, there could be a cell that says "AND foaf:lastName" (and foaf:familyName would also be a row in the table). 

propertyID|mandatory|repeatable|function|functionType|
 ---- |----|----| ---- | ----|
dct:subject|true|true|orderedList|rdf:List|
foaf:firstName|true|false|AND|foaf:familyName|
foaf:familyName|true|false|AND|foaf:firstName|
foaf:name|false|false|OR|foaf:firstName foaf:familyName|

Another option would be to have valueConstraint and valueConstraintType be repeatable but I see at least two dangers with that:
1. the "pairs" would have to be kept in order - possibly not a big danger because the programs that process from CSV to (whatever) would see to that
2. the multiple constraints would have to be compatible, and there is probably a multitude of ways to get that wrong.

At the moment I think we are back to acknowledging an extension for ordered values (and possibly one for ordered properties #15).

**Comment by johnhuck** [comment]
I think this is a good direction to be going with this (putting the orderedList problem with the boolean problem). Ordered list and co-occurrence constraints both relate to meta-structure in instance data beyond the single property. orderedList can only apply to properties that are repeatable.

**Comment by kcoyle** [comment]
@justinlittman We continue to consider this requirement, although we do not yet have a decision. There are some  options, and they depend on the degree to which an actionable declaration must be met. 

1. A column for "ordered" that indicates that if there are multiple statements for that property (the property must be defined as repeatable) the statements must be maintained in a specific order. How that order is managed will depend on the technology used for the metadata.
2. In the manifest for the TAP (see #16 for that discussion) the property can be defined as ordered and perhaps even the type of ordering (- as provided, - numerical, - alphabetical, etc.) could be defined.
3. If it is not expected that input programs or other processing will depend solely on the constraints in the TAP, but that those could be provided elsewhere, the instruction to catalogers that this is an ordered property could be included in the `note` column. 
4. Combining 1 and 3, the `note` column could begin with a keyword ("ordered:") followed by cataloger instructions ("If there is more than one `responsibility statement` put the statements in the order in which they should appear")

If 1 is the preferred solution (and we need to get input from others about this) then it is likely to be defined as an extension, not included in the TAP itself. I am leaning toward a combination of 2 and 3: making it possible to include machine-actionable instructions in a manifest, and giving human-readable instructions in the TAP `note`. 

Can you please let us know if you can work with 3 or 4 for the moment? Those are immediately available, and the other solutions will take more time. It's of great interest to see if TAP can be useful in the BIBFRAME context and it would be a shame if this particular issue held you back. Plus, it would be very interesting to see what TAP profiles one could create for BIBFRAME, even simple ones.

Thanks!

**Comment by kcoyle** [comment]
Additional columns (for which "ordered" could be one) are covered by the config file in dctap-python.
