### ISSUE TITLE
ValueDataType for non-RDF data

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#42]
For RDF data we have defined the `valueDataType` as it is defined in the RDF Schema documentation, which is that it is *always* a literal, and the types are taken from the XML schema data type documentation.

I have already seen a use of `xsd:anyURI` as a TAP `valueDataType` by folks who have not (yet) moved to RDF, but are functioning in a mixed XML/JSON environment. That makes sense for them because they do not have "nodes" in their model. 

Are there other values that we should consider for non-RDF data? Or should we leave it open and allow people to populate the valueDataType with whatever they use in their environment?

**Comment by tombaker** [comment]
@kcoyle 
Using `xsd:anyURI` with `valueDataType` does not contradict the definition of `valueDataType` because it says that the value is a literal. Using `xsd:anyURI` with `valueDataType` while saying that `valueNodeType` is `IRI`, on the other hand, _would_ be a contradiction. Maybe the message should be: "If you do not care about RDF, you do not have to use `valueNodeType` at all" followed by an explanation that this is not an LOD-compatible way to mark URLs.

This is a good topic for the cookbook.

**Comment by tombaker** [comment]
Or perhaps even stronger: "If you are not concerned about RDF compatibility, it is better _not_ to use `valueNodeType`".

> Or should we leave it open and allow people to populate the valueDataType with whatever they use in their environment?

We have provided a "starter set", which I think is the right approach. Beyond that, I think we should _encourage_ people to use value data types that make sense in their own environments. And we could try to collect those types in the cookbook.

**Comment by tombaker** [comment]
Just as the presence of `propertyID` marks the CSV as being (possibly) DCTAP-compatible, the presence of `valueNodeType` could mark the DCTAP instance as being (possibly) RDF-compatible.

**Comment by philbarker** [comment]
FWIW: [JSON Schema](http://json-schema.org/) has a [`type`](http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.1) keyword that can be used to specify the JSON data types allowed for property values, i.e. choice of  "null", "boolean", "object", "array", "number", "string", or "integer". There are also "[defined formats](http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3)" that can be used in conjunction with some values of `type` to specify things like date, time, URI, email address and so on.

I think it would be worth thinking about how these fit into our current column set before assuming only RDF has value node types.

Rather than "duck typing" the TAP, perhaps we could add something about metadata model being targetted to the manifest/TAP metadata?

**Comment by philbarker** [comment]
(ps: yes there is a disconnect between the first paragraph, which would work as value **data** types and the second oneline para about value **node** types. Sorry, I got to thinking about RDF-star and property graphs, which I think may have node types, but didn't write my thoughts.)

**Comment by tombaker** [comment]
@philbarker 
> we could add something about metadata model being targetted to the manifest/TAP metadata?

+1

> worth thinking about how these fit into our current column set before assuming only RDF has value node types.
...
> I got to thinking about RDF-star and property graphs, which I think may have node types, but didn't write my thoughts.

I look forward to hearing more!

**Comment by kcoyle** [comment]
Find place in primer to explain this.

**Comment by kcoyle** [comment]
Added to primer
