### ISSUE TITLE
min/max cardinality

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#50]
There are areas where the concept of "minimum/maximum" is useful in metadata:

1. The minimum and maximum number of instances of a property ("there must be at least one subject but not more than 3")
2. The minimum and maximum values of a numeric data type ("gt 1960 and lt 2030", "GE 7 and LE 18") (now at #57)

The first is a more specific implementation of cardinality, and could possibly be done as a variation on the mandatory/repeatable columns, or could be a different set of columns. The second is a type of valueConstraint. The latter is complicated by needing more than one value, or it needs to be expressed as a pattern.

Should these be worked into the base TAP model?

**Comment by philbarker** [comment]
I think the two examples are quite different. My 2p worth:

1. we're kind of painted into a corner by our choice of mandatory and repeatable as booleans to express cardinality. Had we chosen instead "minimum required instances" and "maximum permitted instances" of a property we could have expressed mandatory and repreatable and the min and max. Unless we change the model, I think new columns (as an extension) would be the only way to go.  Is this a common requirement? Is it important enough to change our model in order to accomodate it?
2. value constraint types can deal with this case. SHACL has minInclusive, minExclusive, maxInclusive, maxExclusive (corresponding to <=,<,>=,> *) How specific the constrain type should be is probably the sort of detail that will vary between implementations, but I would suppport adding "minValue" & "maxValue" or similar as suggestions, defined as being inclusive (so if the minValue allowed is 21, then 21 is allowed).
2.1  There's a variation where a range of values are allowed. This could be possibly be handled by repeating the property statement, but that seems clumsy and inconvenient compared to having a "valueRange" valueConstraint and specifying that the range must be in a format such as x-y (e.g. valueRange = "18-21", means minValue is 18, max value is 21).
3. There's another variation: specifying the min or max length of a string. Credential Engine Registry requires that descriptions are at least 10 characters long. SHACL has sh:minLength and sh:maxLength to express this, so I just used a value constraint of minLength.


* not necessarily in that order

**Comment by kcoyle** [comment]
One more: minimum and maximum length of strings.

The catch is that if these are valueConstraints then it isn't possible to do any other valueConstraints.

**Comment by tombaker** [comment]
@philbarker 
> 1. we're kind of painted into a corner by our choice of mandatory and repeatable as booleans to express cardinality. Had we chosen instead "minimum required instances" and "maximum permitted instances" of a property we could have expressed mandatory and repreatable and the min and max. Unless we change the model, I think new columns (as an extension) would be the only way to go.  Is this a common requirement? Is it important enough to change our model in order to accomodate it?

We went with mandatory/repeatable on the assumption that these would be more familiar to users than min/max, but do we by now have any evidence one way or the other? I like your proposal because min/max is more expressive than mand/repeat (see [the four ways they translate into min/max](https://dctap-python.readthedocs.io/en/latest/elements/mandrepeat/index.html)). I can live with mand/repeat in the core model though would prefer min/max. The only thing that would really make me unhappy would be to have *both* options in the *core* model. Which option to keep in the core should depend on what users prefer (if we have any way to know).

> 2. value constraint types can deal with this case. SHACL has minInclusive, minExclusive, maxInclusive, maxExclusive 

XML Schema and ShEx have these too. These can and should be in an extension.

>    2.1  There's a variation where a range of values are allowed. This could be possibly be handled by repeating the property statement, but that seems clumsy and inconvenient compared to having a "valueRange" valueConstraint and specifying that the range must be in a format such as x-y (e.g. valueRange = "18-21", means minValue is 18, max value is 21).

+1

> 3. There's another variation: specifying the min or max length of a string. Credential Engine Registry requires that descriptions are at least 10 characters long. SHACL has sh:minLength and sh:maxLength to express this, so I just used a value constraint of minLength.

XML Schema and ShEx also have these, so yes, good candidates for an extension.

> 
> * not necessarily in that order

**Comment by tombaker** [comment]
@kcoyle 
> One more: minimum and maximum length of strings.
> 
> The catch is that if these are valueConstraints then it isn't possible to do any other valueConstraints.

Could there not be two extension elements such as `minLiteralValueLength` and `maxLiteralValueLength` (preferably with shorter names)? It would of course make no sense to have values for these unless the value were a literal.

**Comment by kcoyle** [comment]
@tombaker Yes, I could see these as columns for minLen and maxLen or something like that. I am seeing these constraints in both the DataCite and the RDA/LOM data. The max length strikes me as a bit "old fashioned" - we seem to be beyond having to limit the length of strings - but it does appear that it is still used. As we keep finding more requirements for a profile I wonder if we shouldn't be presenting TAP not itself as a table but as a selection of columns that can be used to create a table. I'm going to think more about how we could do that. Maybe a very limited core and define the rest based on needs. If you need to define length of strings, here are two columns to do that. If you need to define RDF nodes, here's the column for that. etc.

**Comment by philbarker** [comment]
@kcoyle 
> The catch is that if these are valueConstraints then it isn't possible to do any other valueConstraints.

You could have more than one row with the same property, once for each valueConstraint.

I very much like your idea of TAP as a collection of columns, but I'm less keen on adding columns for each valueConstraintType that needs adidng.

**Comment by kcoyle** [comment]
Phil, if we allow/suggest more than one row with the same property, we have to declare whether multiple instances of a property within the same shape is an AND or an OR. We have previously postulated an OR, such as when a property can have either an IRI or a string value, and we want to give a valueConstraint for one or both. I'll need examples to play with as I find it hard to think about this in the abstract. I'll look for or make some and then post back here.

**Comment by kcoyle** [comment]
See some related discussion in #12 . We closed that because we solved the base problem, but had some side discussion about using separate rows.

**Comment by philbarker** [comment]
Ah, I thought repeating a line implied an AND relationship. I would argue that rows are independent of each other and the requirements in every row should be "honored", but I'm sure other readings could make sense. 

The example in #12 works because rows 1,2 AND 3 apply, but because only row 1 is mandatory (the subject property must be present) there is an option of using row 2 (Literal values) OR row 3 (URIs) to provide a value.

Here's a copy of that example for ease of reference:

shapeID|propertyID|propertyLabel|mandatory|repeatable|valueNodeType|valueDataType|valueConstraint|valueConstraintType|valueShape|note
----|---- | ---- |----|----| ---- | ---- |---- |---- |----|----
book|dct:subject | ---- |true|true| ---- | ---- |---- |---- |  |----
 ||dct:subject|subject|false|true|LITERAL|xsd:string|`@en`,`@fr`|languageTag||
||dct:subject|subject|false|true|IRI||http://id.loc.gov|||

Which I would interpret as saying 
Line 1: there must be a subject
Line 2: subject may be a LITERAL
Line 3: subject may be a IRI

**Comment by philbarker** [comment]
PS: my final comment on that suggestion example in the context of #12 was that it is "not ideal because there is no way of saying subject may NOT be a BNODE." -- having columns for min and max number of repeats instead of mandatory and repeatable could fix that, by setting the max number of dct:subject properties with a BNODE value to 0.

**Comment by kcoyle** [comment]
@philbarker Interesting. What that means to me is that we define the mandatory/repeatable not as defining the cardinality of the property, but as defining the cardinality of the entire statement. We ran into this before where the property was mandatory, but there was a choice of statement constraints, as in your example. 

The rules that you provide make sense but do they work in general as validation? Rewording this a bit:
1. dct:subject with no valueType defined is mandatory (dct:subject can be anything)
2: dct:subject as a LITERAL is optional
3: dct:subject as an IRI is optional

It seems to me that whatever dct:subject is encountered is mandatory, but 2 and 3 would still be optional because the rows are independent of each other. The row with mandatory does not define dct:subject in general. (Can anyone model this in SHACL or ShEx?) I think it needs a mandatory shape that has optional statement constraints. 

You might recall that I tried this in #12 but there was the problem of having dct:subject having a value of dct:subject:

shapeID|shapeLabel|propertyID|propertyLabel|mandatory|repeatable|valueNodeType|valueDataType|valueConstraint|valueConstraintType|valueShape|note
----|----|---- | ---- |----|----| ---- | ---- |---- |---- |----|----
book|----|dct:subject | ---- |true|true| ---- | ---- |---- |---- |subject|----
subject||dct:subject|subject|false|true|LITERAL|xsd:string|@en,@fr|languageTag||
|||dct:subject|subject|false|true|IRI||http://id.loc.gov|||

We're back to two things that we've struggled with: 
* cardinality of shapes
* managing AND OR NOT

I think we should make these (separately) a discussion for a meeting so we can hash this out. (And include your idea of using max number of 0 to model NOT.)

**Comment by philbarker** [comment]
+1 @kcoyle definitely needs thinking through carefully.

**Comment by kcoyle** [comment]
When using numerical min/max for **cardinality**, I presume that 0 minimum means that there is no minimum applied. Are there uses of this that interpret '0' as a prohibition? SHACL says:

> If the minimum cardinality value is 0 then this constraint is always satisfied and so may be omitted

That seems to be our mandatory=FALSE

Also, what would we use for maximum unbounded? The "1..n" uses "n" for unbounded, but other implementations use "-1". Shex has:

> max of -1 is treated as unbounded
 
The SHACL document is silent on max=unlimited as far as I can see, just as the ShEx document seems to be silent on mandatory=false. 

Here's my attempted summary:

|function|TAP|numerical min/max|
|----|----|----|
|not mandatory|mandatory=FALSE|minimum=0|
|mandatory, unlimited|mandatory=TRUE| ??|
|mandatory "n"| not possible | minimum="n"|
|not repeatable|repeatable=FALSE|maximum=0|
|repeatable unlimited | repeatable=TRUE | maximum=-1|
|repeatable "n" times| not possible | maximum="n"|

We have already said that where cardinality is not provided that downstream processes may make their own decisions. This means that not specifying mandatory or repeatable would generally be interpreted to mean "not mandatory, but yes repeatable".

**Comment by philbarker** [comment]
I think we should avoid the use of non-integer values such as `n` for unbounded. If it's unbounded, then there is no constraint, so there is no need to have a value for the constraint.

**Comment by kcoyle** [comment]
@philbarker If we don't use something for "unbounded" then

- missing "min" means 1) not mandatory or 2) mandatory, unbounded
- missing "max" means 1) not repeatable or 2) repeatable, unbounded

Is that what we want? I really hate for "missing" to have meaning because it's hard for readers to know what it means. I favor explicit values over implicit ones.

**Comment by philbarker** [comment]
> If we don't use something for "unbounded" then
> 
> - missing "min" means 1) not mandatory or 2) mandatory, unbounded
No constraint, so no minimum number occurences, i.e. not mandatory (I don't think a minimum can be unbounded)

> - missing "max" means 1) not repeatable or 2) repeatable, unbounded
No constraint, so no maximum number of occurences, i.e. repeatable unbounded.

> 
> Is that what we want? I really hate for "missing" to have meaning because it's hard for readers to know what it means. I favor explicit values over implicit ones.

Well, the entire column is optional: how would you interpret a TAP with no min/max (or repeatable/mandatory) column?

But if it avoids an argument, I wouldn't mind `-1` for unbounded; however, that leaves the interpretation on missing and null values open, which may be less clear for readers.

**Comment by kcoyle** [comment]
What we've said in the past about missing values or columns is that they have no inherent or default meaning. Downstream processes can apply their own defaults, but TAP is silent on them.

**Comment by kcoyle** [comment]
Although, add the possibility of using valueconstrainttype? A valueconstrainttype of something like "m/mCardinality" could have a value of "1..0".  I could add that to the cookbook.

**Comment by kcoyle** [comment]
Added to cookbook
