### ISSUE TITLE
DCAT example has no theme

### ISSUE THREAD

**Issue by philbarker** [dcmi/dctap#58]
Dataset should have a property dcat:theme, instead it has dcat:themeTaxonomy (with label Theme).  I think there also needs to be a Concept shape for the value of the theme property.

**Comment by kcoyle** [comment]
Thanks, Phil, yes, DCAT:Catalog has themetaxonomy, and Dataset has theme. I bet that was the spreadsheet program being helpful. 

I need to do a full review of the DCAT-AP and I'll look back at the full DCAT-AP with your comments in mind. The documentation doesn't show those properties having skos:Concept values, but maybe that information is buried in the document in a way that it isn't obvious. That DCAT-AP TAP is also missing the connecting arcs between shapes, and I'm still not sure where those take place, but I'm getting a better idea working on a TAP based on some actual DCAT data, not the DCAT-AP specs. In the actual data the thing listed as the Class actually represents a locally identified `thing` of that class, and that locally identified thing has the outgoing arcs. At least, I think it works that way, and will try that out when I get back to the big DCAT-AP. The small data example (from Eurostat) is making more sense to me so I'll complete that, since it is in fact an AP of the DCAT-AP and quite a bit smaller. I think this TAP will illustrate the utility of being able to define data based on DCAT-AP.

**Comment by kcoyle** [comment]
There is an [update to the DCAT-AP](https://github.com/SEMICeu/DCAT-AP/blob/2.1.0-draft/releases/2.1.0/dcat-ap_2.1.0.pdf) in progress. This is not yet done so there may still be changes. The [previous release folder](https://github.com/SEMICeu/DCAT-AP/tree/master/releases/2.0.1) shows what may accompany it.

**Comment by kcoyle** [comment]
DCAT-AP TAP example fixed.
