### ISSUE TITLE
Boolean values

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#7]
The [XML Schema](http://www.w3.org/TR/xmlschema11-2/) standard boolean values are:

booleanRep ::= 'true' | 'false' | '1' | '0'

Our boolean columns are "mandatory" and "repeatable" and in examples we've used "y" and "n" for "yes" and "no". This seems to fit with the question: is this mandatory? is this repeatable?

"true/false" might also be natural here, but anyone who isn't a coder probably doesn't think in terms of 1 and 0 as answers to the question.

Also, any language terms (true/false, yes/no) are obviously language specific.

- Do we want to limit to the valid XML schema values?
- Do we want to define a specific list of valid values for the TAP?
- Do we want to leave it open so that profile developers and applications can apply their own values? (Perhaps limiting interoperability)
- Is there a way to include the definition in an external file so that it can be defined along with the profile?

**Comment by tombaker** [comment]
@kcoyle 
> Do we want to leave it open so that profile developers and applications can apply their own values? (Perhaps limiting interoperability)

We can provide suggested values and encourage developers of DCTAP applications to support those values. And if people see examples that use suggested values, they will most likely follow those suggestions. But people will adapt or extend the model for their own purposes, and they will do this in uncontrolled ways - eg with extra columns or novel value constraint types, or with usages that do not fit our guidelines (eg, property IDs as simple strings instead of IRIs), or with column headings and values in Spanish or Chinese. In fact, this should be encouraged.

I see no need to worry about this sort of uncontrolled adaptation as long as we do not try to position DCTAP as a generic exchange format. While it might serve as an exchange format within a given community of practice, where a community has agreed on conventions around what values to use for the boolean columns or even to the interpretation of given columns, we should IMO avoid implying that DCTAP itself provides meaningful interoperabiity. That is, we should not encourage people to think that they can take some CSV found on the Web, which happens to use DCTAP column headers, and use it to validate data precisely in the way its authors intended.

**Comment by philbarker** [comment]
This could be another thing (along with namespace ids and local column headings) that is specified in a file that accompanies the csv.

**Comment by philbarker** [comment]
CSV on the Web does [this](https://www.w3.org/TR/tabular-data-primer/#boolean-format)

**Comment by kcoyle** [comment]
We can propose that profile creators use the XML schema standard:

booleanRep ::= 'true' | 'false' | '1' | '0'

with "1|0" being universal (not bound by language). Anyone wanting to use other than these two options would need to define their choice in a related manifest file. As Phil said, the CSV on the Web project uses:

`"datatype": { `
`  "base": "boolean", `
 ` "format": "Yes|No" `
`}`

This would likely be re-interpreted as "1|0" in programs that reformat the CSV.

**Comment by kcoyle** [comment]
Proposed language:

The columns `mandatory` and `repeatable` take Boolean values. Boolean values are a pair of values representing either *true* or *false*. The XML Schema standard (link) gives these two possible sets of values:

true/false
1/0

These values are commonly known and will be recognized by many programming languages and routines. Using the numbers 1 and 0 avoids requiring users to conform to the English language terms of "true" and "false". However, many persons not familiar with this use of 1 and 0 may not find these values natural. There is no reason not to use other binary values like "yes|no" or the equivalent in the language of the profile creators and users as long as the values chosen are documented for downstream users.

**Comment by tombaker** [comment]
@kcoyle 
> ... There is no reason not to use other binary values like "yes|no" or the equivalent in the language of the profile creators and users as long as the values chosen are documented for downstream users.

I like this position and the explanation.

**Comment by kcoyle** [comment]
In TAP primer under heading Property Cardinality

https://github.com/dcmi/dctap/blob/main/TAPprimer.md#property-cardinality
